[aliases]
ll = "ls -l"
la = "ls -la"
lzg = "lazygit"
lzd = "lazydocker"
ls = "eza --sort type --icons -F -H --group-directories-first -1"
neofetch = "fastfetch"
cat = "bat -p"
rm = "rm -i"
mv = "mv -n"
r = "rsync --archive --verbose --human-readable --progress --one-file-system --ignore-existing"
sc = "systemctl"
scu = "systemctl --user"
jc = "journalctl -ex --unit"
jcu = "journalctl --user -ex --unit"
hms = "home-manager switch"
code = "codium"
v = "nvim"
y = "yazi"
dc = "docker compose"
n2ne = "nvim $HM_PATH/nixpkgs/node/packages.json"
n2ni = "node2nix -i $HM_PATH/nixpkgs/node/packages.json -e $HM_PATH/nixpkgs/node/node-env.nix -o $HM_PATH/nixpkgs/node/packages.nix -c $HM_PATH/nixpkgs/node/default.nix"

[variables]
HM_PATH = "$HOME/.config/home-manager"
LIBVIRT_DEFAULT_URI = "qemu:///system"
QT_QPA_PLATFORM = "xcb;wayland"
QT_STYLE_OVERRIDE = "kvantum"
GTK_THEME = "Colloid-Dark-Nord"
GTK_CURSOR = "Colloid-dark-cursors"
XCURSOR_THEME = "Colloid-dark-cursors"
GTK_ICON = "Win11"
