[aliases]
ls2 = "ls -TL=2"
ls3 = "ls -TL=3"
lsa = "ls -T"
ll = "ls -l"
lla = "ls -lT"
ll2 = "ls -lTL=2"
ll3 = "ls -lTL=3"
la = "ls -la"
la2 = "ls -laTL=2"
la3 = "ls -laTL=3"
gtl = "lazygit"
dcl = "lazydocker"
ls = "eza --sort type --icons -F -H --group-directories-first -1"
neofetch = "fastfetch"
cat = "bat -p"
rm = "rm -i"
mv = "mv -n"
r = "rsync --archive --verbose --human-readable --progress --one-file-system --ignore-existing"
sc = "systemctl"
scu = "systemctl --user"
jc = "journalctl -ex --unit"
jcu = "journalctl --user -ex --unit"
hmc = "nvim $HM_PATH/common/config.toml"
hmd = "nvim $HM_PATH"
hms = "home-manager switch"
code = "codium"
nv = "nvim ."
n2ne = "nvim $HM_PATH/nixpkgs/node/packages.json"
n2ni = "node2nix -i $HM_PATH/nixpkgs/node/packages.json -e $HM_PATH/nixpkgs/node/node-env.nix -o $HM_PATH/nixpkgs/node/packages.nix -c $HM_PATH/nixpkgs/node/default.nix"


[variables]
HM_PATH = "$HOME/.config/home-manager"
LIBVIRT_DEFAULT_URI = "qemu:///system"
QT_QPA_PLATFORM = "xcb;wayland"
QT_STYLE_OVERRIDE = "kvantum"
GTK_THEME = "Colloid-Dark-Nord"
GTK_CURSOR = "Colloid-dark-cursors"
XCURSOR_THEME = "Colloid-dark-cursors"
GTK_ICON = "Win11"
