[aliases]
ls2 = "ls -TL=2"
ls3 = "ls -TL=3"
lsa = "ls -T"
ll = "ls -l"
lla = "ls -lT"
ll2 = "ls -lTL=2"
ll3 = "ls -lTL=3"
la = "ls -la"
la2 = "ls -laTL=2"
la3 = "ls -laTL=3"
lzd = "lazydocker"
lzg = "lazygit"
nano = "micro"
ls = "eza --sort type --icons -F -H --group-directories-first -1"
neofetch = "fastfetch"
cat = "bat -p"
# sshk = "ssh-keygen -t ed25519 -M -O -C"
rm = "rm -i"
mv = "mv -n"
r = "rsync --archive --verbose --human-readable --progress --one-file-system --ignore-existing"
sc = "systemctl"
scu = "systemctl --user"
jc = "journalctl -ex --unit"
jcu = "journalctl --user -ex --unit"

[variables]
EDITOR = "micro"
LIBVIRT_DEFAULT_URI = "qemu:///system"
QT_QPA_PLATFORM = "xcb;wayland"
QT_STYLE_OVERRIDE = "kvantum"
GTK_THEME = "Colloid-Dark-Nord"
GTK_CURSOR = "Colloid-dark-cursors"
XCURSOR_THEME = "Colloid-dark-cursors"
GTK_ICON = "Win11"