---
name: Update flake

"on":
  push:
  pull_request:
  schedule:
    - cron: 0 5 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: determinatesystems/nix-installer-action@main
      - uses: determinatesystems/magic-nix-cache-action@main
      - uses: determinatesystems/flake-checker-action@main

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Update flake inputs
        run: |
          nix flake update nix-stash --accept-flake-config
          git commit -m "Updated flake inputs" flake.lock || true

      - name: Push commit with updated inputs
        run: |
          git pull --rebase --autostash
          git push
